import { readdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { defineConfig } from 'vite';

// One entry per case page generated by scripts/build-pages.mjs.
const cases = Object.fromEntries(
  readdirSync(resolve(__dirname, 'work')).map((slug) => [slug, resolve(__dirname, 'work', slug, 'index.html')]),
);

export default defineConfig({
  build: {
    rollupOptions: {
      input: { main: resolve(__dirname, 'index.html'), ...cases },
    },
  },
});
